sudo: required
dist: trusty
language: node_js
node_js:
- '6'
git:
  depth: 3
addons:
  ssh_known_hosts:
  - web-standards.ru
  - wsd.events
before_deploy:
- .travis/set-up-ssh
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
